version: '3'
services:
  db:
    image: postgres
    container_name: zettablock-db
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  zettablock-backend:
    build:
      context: .
      dockerfile: ./docker/Docker.server.node/Dockerfile
    image: zettablock-node
    env_file: .env
    container_name: zettablock-backend
    volumes:
      - ./server:/code/server
    ports:
      - '80:80'
    depends_on:
      - db
    links:
      - db:postgres
    expose:
      - 80
